compatibility_date = "2023-03-14"
compatibility_flags = [ "nodejs_compat" ]

kv_namespaces = [
    { binding = "CRAWLER_KV", id = "3e0e8a0ef4154797b8ae7827b599f140" }
]
r2_buckets = [
    { binding = "IMAGE_R2", bucket_name = "newsletter-image" }
]
